(() => {
 'use strict';document.documentElement.classList.add('js');
 const header=document.querySelector('.header'),chapters=[...document.querySelectorAll('.chapter')],nav=[...document.querySelectorAll('.header nav a')];let raf=0;
 function scroll(){raf=0;header.classList.toggle('is-scrolled',scrollY>45);let active='';for(const chapter of chapters)if(chapter.getBoundingClientRect().top<innerHeight*.4)active=chapter.id;nav.forEach(a=>{if(a.hash==='#'+active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}
 addEventListener('scroll',()=>{if(!raf)raf=requestAnimationFrame(scroll);},{passive:true});scroll();
 const box=document.querySelector('#lightbox'),works=[...document.querySelectorAll('.work')];let selected=0,trigger=null;
 const stories=[
  {heading:'O desenho acompanha o braço.',region:'Braço e antebraço',composition:'Dragão, flores de cerejeira e linhas curvas',text:'O dragão percorre a extensão do braço entre flores. As curvas ligam os elementos e acompanham a passagem pelo cotovelo. Preto e vermelho se alternam ao longo da composição.',focus:'45% 58%'},
  {heading:'Duas figuras em diálogo.',region:'Coxa',composition:'Kitsunes e fios vermelhos',text:'As duas kitsunes ocupam posições diferentes dentro da composição. O fio vermelho atravessa os espaços entre as figuras e conduz o olhar de uma para a outra.',focus:'60% 55%'},
  {heading:'Preto, escamas e respiro.',region:'Peito e braço',composition:'Dragão em blackwork',text:'As escamas definem o corpo do dragão, enquanto áreas de preto dão peso à composição. O desenho se estende do peito ao braço, acompanhando a transição do ombro.',focus:'58% 40%'},
  {heading:'Uma composição que se abre.',region:'Peito',composition:'Mariposa e ramos florais',text:'A mariposa ocupa o centro. As flores se distribuem para os lados, criando uma composição aberta que acompanha a parte superior do peito.',focus:'50% 49%'},
  {heading:'O gesto vira direção.',region:'Ombro e braço',composition:'Linhas abstratas em preto e vermelho',text:'Curvas largas e pontas finas alternam a direção do traço. O vermelho cruza o preto, criando diferentes percursos ao redor do ombro.',focus:'53% 36%'},
  {heading:'Botânica em extensão.',region:'Braço',composition:'Folhagens alongadas',text:'As folhas se conectam por linhas compridas, seguindo a extensão do braço. A composição alterna áreas preenchidas e espaços de pele.',focus:'50% 55%'}
 ];
 function setPhoto(mode){document.querySelector('.project-photo').classList.toggle('is-detail',mode==='detail');document.querySelectorAll('[data-photo]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.photo===mode)));}
 document.querySelectorAll('[data-photo]').forEach(button=>button.addEventListener('click',()=>setPhoto(button.dataset.photo)));
 function show(index){selected=(index+works.length)%works.length;const work=works[selected],story=stories[selected];document.querySelector('#lightbox-title').textContent=work.dataset.title;document.querySelector('#lightbox-style').textContent=work.dataset.style;const img=document.querySelector('#lightbox-image');img.src=work.href;img.alt=work.querySelector('img').alt;img.style.transformOrigin=story.focus;document.querySelector('#lightbox-counter').textContent=`${selected+1} de ${works.length}`;document.querySelector('#project-heading').textContent=story.heading;document.querySelector('#project-description').textContent=story.text;document.querySelector('#project-region').textContent=story.region;document.querySelector('#project-composition').textContent=story.composition;setPhoto('full');box.scrollTop=0;}
 works.forEach((work,index)=>work.addEventListener('click',event=>{if(event.ctrlKey||event.metaKey||event.shiftKey||event.altKey)return;event.preventDefault();trigger=work;show(index);box.showModal();document.body.classList.add('modal-open');document.dispatchEvent(new Event('ink-modal'));}));
 document.querySelector('.close-lightbox').addEventListener('click',()=>box.close());document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>show(selected+Number(button.dataset.step))));
 box.addEventListener('keydown',event=>{if(event.key==='ArrowRight'){event.preventDefault();show(selected+1);}if(event.key==='ArrowLeft'){event.preventDefault();show(selected-1);}});
 box.addEventListener('close',()=>{document.body.classList.remove('modal-open');trigger?.focus({preventScroll:true});document.dispatchEvent(new Event('ink-modal'));});
 document.querySelector('.lightbox-contact').addEventListener('click',()=>{box.close();setTimeout(()=>{document.querySelector('[name="ideia"]').focus();},0);});
 const form=document.querySelector('form'),result=document.querySelector('.form-result');
 form.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(form),name=data.get('nome').trim();const message=`Olá, Ítala! ${name?'Meu nome é '+name+'. ':''}Gostaria de conversar sobre uma tatuagem.\n\nIdeia: ${data.get('ideia').trim()}\nRegião do corpo: ${data.get('regiao').trim()}\nTamanho aproximado: ${data.get('tamanho').trim()}\nCidade: ${data.get('cidade')}.`;const link=document.querySelector('#whatsapp-message');link.href='https://wa.me/5562993227097?text='+encodeURIComponent(message);result.hidden=false;link.focus();});
 form.addEventListener('input',()=>result.hidden=true);
})();
